import { MOCK_API_KEY } from '@core/tools/braveSearchTool/constants';
import {
  DEFAULT_ABOUT_ME_FILE_NAME,
  DEFAULT_AGENT_PERSONALITIES_DIRECTORY,
  DEFAULT_AGENT_PERSONALITY,
  DEFAULT_AGENT_WORKSPACE_DIRECTORY_NAME,
  DEFAULT_APPLICATION_PORT,
  DEFAULT_BRAVE_SEARCH_API_KEY,
  DEFAULT_BRAVE_SEARCH_API_URL,
  DEFAULT_GEMINI_MODEL,
  DEFAULT_GOOGLE_CLIENT_ID,
  DEFAULT_GOOGLE_CLIENT_SECRET,
  DEFAULT_GOOGLE_GEMINI_API_KEY,
  DEFAULT_GOOGLE_REFRESH_TOKEN,
  DEFAULT_MODEL_NAME,
  DEFAULT_MODEL_TYPE,
  DEFAULT_OLLAMA_BASE_URL,
  DEFAULT_OPENAI_BASE_URL,
  DEFAULT_RECORDINGS_DIR,
  DEFAULT_SEARCH_ENGINE,
  DEFAULT_SYSTEM_PROMPTS_DIRECTORY,
  ModelType,
  SearchEngine,
} from './constants';

export const AppConfigFunction = () =>
  ({
    CUSTOM_CA_CERT_PATH: process.env.CUSTOM_CA_CERT_PATH,
    OLLAMA_BASE_URL: process.env.OLLAMA_BASE_URL || DEFAULT_OLLAMA_BASE_URL,
    MODEL_NAME: process.env.MODEL_NAME || DEFAULT_MODEL_NAME,
    RECORDINGS_DIR: process.env.RECORDINGS_DIR || DEFAULT_RECORDINGS_DIR,
    APPLICATION_PORT:
      Number.parseInt(process.env.APPLICATION_PORT || '') ||
      DEFAULT_APPLICATION_PORT,
    DEBUG: Boolean(process.env.DEBUG === 'true') || false,
    TRANSCRIPTION_SERVER_ENDPOINT:
      process.env.TRANSCRIPTION_SERVER_ENDPOINT || '',
    VOICE_SYNTHESIS_SERVER_ENDPOINT:
      process.env.VOICE_SYNTHESIS_SERVER_ENDPOINT || '',
    AGENT_PERSONALITY:
      process.env.AGENT_PERSONALITY || DEFAULT_AGENT_PERSONALITY,
    SYSTEM_PROMPTS_DIRECTORY:
      process.env.SYSTEM_PROMPTS_DIRECTORY || DEFAULT_SYSTEM_PROMPTS_DIRECTORY,
    AGENT_PERSONALITIES_DIRECTORY:
      process.env.AGENT_PERSONALITY_DIRECTORY ||
      DEFAULT_AGENT_PERSONALITIES_DIRECTORY,
    ABOUT_ME_FILE_NAME:
      process.env.ABOUT_ME_FILE_NAME || DEFAULT_ABOUT_ME_FILE_NAME,
    GOOGLE_GEMINI_API_KEY:
      process.env.GOOGLE_GEMINI_API_KEY || DEFAULT_GOOGLE_GEMINI_API_KEY,
    GEMINI_MODEL: process.env.GEMINI_MODEL || DEFAULT_GEMINI_MODEL,
    BRAVE_SEARCH_API_KEY:
      process.env.BRAVE_SEARCH_API_KEY || DEFAULT_BRAVE_SEARCH_API_KEY,
    BRAVE_SEARCH_API_URL:
      process.env.BRAVE_SEARCH_API_URL || DEFAULT_BRAVE_SEARCH_API_URL,
    SERPAPI_API_KEY: process.env.SERPAPI_API_KEY || MOCK_API_KEY,
    LOCATION_CITY: process.env.LOCATION_CITY,
    LOCATION_REGION: process.env.LOCATION_REGION,
    LOCATION_REGION_CODE: process.env.LOCATION_REGION_CODE,
    LOCATION_COUNTRY: process.env.LOCATION_COUNTRY,
    LOCATION_COUNTRY_NAME: process.env.LOCATION_COUNTRY_NAME,
    LOCATION_COUNTRY_CODE: process.env.LOCATION_COUNTRY_CODE,
    LOCATION_COUNTRY_CODE_ISO3: process.env.LOCATION_COUNTRY_CODE_ISO3,
    LOCATION_COUNTRY_CAPITAL: process.env.LOCATION_COUNTRY_CAPITAL,
    LOCATION_COUNTRY_TLD: process.env.LOCATION_COUNTRY_TLD,
    LOCATION_CONTINENT_CODE: process.env.LOCATION_CONTINENT_CODE,
    LOCATION_IN_EU: process.env.LOCATION_IN_EU === 'true',
    LOCATION_POSTAL: process.env.LOCATION_POSTAL,
    LOCATION_LATITUDE: process.env.LOCATION_LATITUDE
      ? Number.parseFloat(process.env.LOCATION_LATITUDE)
      : 0,
    LOCATION_LONGITUDE: process.env.LOCATION_LONGITUDE
      ? Number.parseFloat(process.env.LOCATION_LONGITUDE)
      : 0,
    LOCATION_TIMEZONE: process.env.LOCATION_TIMEZONE,
    LOCATION_UTC_OFFSET: process.env.LOCATION_UTC_OFFSET,
    LOCATION_COUNTRY_CALLING_CODE: process.env.LOCATION_COUNTRY_CALLING_CODE,
    LOCATION_CURRENCY: process.env.LOCATION_CURRENCY,
    LOCATION_CURRENCY_NAME: process.env.LOCATION_CURRENCY_NAME,
    LOCATION_LANGUAGES: process.env.LOCATION_LANGUAGES,
    LOCATION_COUNTRY_AREA: process.env.LOCATION_COUNTRY_AREA
      ? Number.parseFloat(process.env.LOCATION_COUNTRY_AREA)
      : 0,
    LOCATION_COUNTRY_POPULATION: process.env.LOCATION_COUNTRY_POPULATION
      ? Number.parseInt(process.env.LOCATION_COUNTRY_POPULATION)
      : 0,
    LOCATION_ASN: process.env.LOCATION_ASN,
    LOCATION_ORG: process.env.LOCATION_ORG,
    MODEL_TYPE: (process.env.MODEL_TYPE || DEFAULT_MODEL_TYPE) as ModelType,
    SEARCH_ENGINE: (process.env.SEARCH_ENGINE ||
      DEFAULT_SEARCH_ENGINE) as SearchEngine,
    AGENT_WORKSPACE_DIRECTORY_NAME:
      process.env.AGENT_WORKSPACE_DIRECTORY_NAME ||
      DEFAULT_AGENT_WORKSPACE_DIRECTORY_NAME,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || DEFAULT_GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET:
      process.env.GOOGLE_CLIENT_SECRET || DEFAULT_GOOGLE_CLIENT_SECRET,
    GOOGLE_REFRESH_TOKEN:
      process.env.GOOGLE_REFRESH_TOKEN || DEFAULT_GOOGLE_REFRESH_TOKEN,
    OPENAI_API_KEY: process.env.OPENAI_API_KEY || '',
    OPENAI_BASE_URL: process.env.OPENAI_BASE_URL || DEFAULT_OPENAI_BASE_URL,
  }) as const;

export type AppConfig = ReturnType<typeof AppConfigFunction>;
